name = "fsir"
pretrained_path = ""
save_snapshots = true
deterministic = false
seed = 42

[trainer]
log_every_n_steps = 200
gradient_clip_val = 1.0
gradient_clip_algorithm = "norm"
lr = 1e-4
step_size = 200000
gamma = 0.7

[datasets]
batch_size = 32
num_workers = 4
pin_memory = true

[datasets.train]
img_path = "/Users/fuzz/Downloads/Set5"
patch_size = 120
sf_list = [1, 2, 3, 4]
sigma_max = 0.01

[datasets.val]
img_path = "/Users/fuzz/Downloads/Set5"
kernel_path = "src/kernels/kernels_12.pt"
k_idx = 0
sf = 3
sigma = 0

[datasets.test]
img_path = "/Users/fuzz/Downloads/Set5"
kernel_path = ""
k_idx = 0
sf = 3
sigma = 0